apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-wind
data:
  API_URL: "https://dmigw.govcloud.dk/v1/forecastedr/collections/harmonie_dini_sf/cube"
  PARAMETER_NAME: "wind-speed-10m"
  TOPIC: "weather-wind4"
  BOOTSTRAP_SERVERS: "kafka-g5:9092"
  POLL_INTERVAL: "120"
  API_KEY: "9c1728d6-69ec-4be2-8e6c-72dee4dc44df"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-temp
data:
  API_URL: "https://dmigw.govcloud.dk/v1/forecastedr/collections/harmonie_dini_sf/cube"
  PARAMETER_NAME: "temperature-2m"
  TOPIC: "weather-temp4"
  BOOTSTRAP_SERVERS: "kafka-g5:9092"
  POLL_INTERVAL: "120"
  API_KEY: "9c1728d6-69ec-4be2-8e6c-72dee4dc44df"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-sun
data:
  API_URL: "https://dmigw.govcloud.dk/v1/forecastedr/collections/harmonie_dini_sf/cube"
  PARAMETER_NAME: "direct-solar-exposure"
  TOPIC: "weather-sun4"
  BOOTSTRAP_SERVERS: "kafka-g5:9092"
  POLL_INTERVAL: "120"
  API_KEY: "9c1728d6-69ec-4be2-8e6c-72dee4dc44df"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-1-g5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-1-g5
  template:
    metadata:
      labels:
        app: kafka-producer-1-g5
    spec:
      containers:
      - name: producer
        image: arejula11/kafka-producer:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: kafka-producer-wind
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-2-g5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-2-g5
  template:
    metadata:
      labels:
        app: kafka-producer-2-g5
    spec:
      containers:
      - name: producer
        image: arejula11/kafka-producer:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: kafka-producer-temp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-3-g5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-3-g5
  template:
    metadata:
      labels:
        app: kafka-producer-3-g5
    spec:
      containers:
      - name: producer
        image: arejula11/kafka-producer:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: kafka-producer-sun
