apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-wind
data:
  API_URL: "https://dmigw.govcloud.dk/v1/forecastedr/collections/harmonie_dini_sf/cube"
  PARAMETER_NAME: "wind-speed-10m"
  TOPIC: "weather-wind"
  BOOTSTRAP_SERVERS: "kafka-g5-controller-headless:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  POLL_INTERVAL: "10800"
  API_KEY: "9c1728d6-69ec-4be2-8e6c-72dee4dc44df"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-temp
data:
  API_URL: "https://dmigw.govcloud.dk/v1/forecastedr/collections/harmonie_dini_sf/cube"
  PARAMETER_NAME: "temperature-2m"
  TOPIC: "weather-temp"
  BOOTSTRAP_SERVERS: "kafka-g5-controller-headless:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  POLL_INTERVAL: "10800"
  API_KEY: "9c1728d6-69ec-4be2-8e6c-72dee4dc44df"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-sun
data:
  API_URL: "https://dmigw.govcloud.dk/v1/forecastedr/collections/harmonie_dini_sf/cube"
  PARAMETER_NAME: "direct-solar-exposure"
  TOPIC: "weather-sun"
  BOOTSTRAP_SERVERS: "kafka-g5-controller-headless:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  POLL_INTERVAL: "10800"
  API_KEY: "9c1728d6-69ec-4be2-8e6c-72dee4dc44df"