apiVersion: v1
kind: ConfigMap
metadata:
  name: energy-ml-config
  namespace: bd-bd-gr-05
data:
  # Data paths
  DATA_BASE_PATH: "/data"
  
  # Model configuration
  N_TRAINING_YEARS: "4"
  FORECAST_DAYS: "3"
  
  # Spark configuration
  SPARK_MASTER: "local[*]"
  SPARK_EXECUTOR_MEMORY: "8g"
  SPARK_DRIVER_MEMORY: "8g"
  SPARK_EXECUTOR_CORES: "4"