#!/bin/bash

# Quick setup guide for Dashboard Hive Integration

echo "🚀 Dashboard Hive Integration - Quick Setup"
echo ""
echo "Step 1: Configure Environment Variables"
echo "========================================"
echo "Edit Dashboard/backend/.env:"
echo "  HIVE_HOST=your_hive_server"
echo "  HIVE_PORT=10000"
echo "  HIVE_USER=your_username"
echo "  HIVE_PASSWORD=your_password"
echo ""

echo "Step 2: Test Local Development"
echo "==============================="
echo "cd Dashboard/backend"
echo "npm install"
echo "npm run start:dev"
echo ""
echo "Then test: curl http://localhost:3000/api/hive/predictions?limit=10"
echo ""

echo "Step 3: Configure Kubernetes Deployment"
echo "========================================"
echo "cd Dashboard/k8s"
echo ""
echo "3a. Update k8s/configmap.yaml:"
echo "    HIVE_HOST=your_hive_server"
echo "    HIVE_PORT=10000"
echo ""
echo "3b. Update k8s/secret.yaml:"
echo "    HIVE_USER=your_username"
echo "    HIVE_PASSWORD=your_password"
echo ""
echo "3c. Update k8s/backend.yaml & frontend.yaml:"
echo "    image: your-registry/dashboard-backend:latest"
echo "    image: your-registry/dashboard-frontend:latest"
echo ""
echo "3d. Update k8s/ingress.yaml:"
echo "    - host: dashboard-api.yourdomain.com"
echo "    - host: dashboard.yourdomain.com"
echo ""

echo "Step 4: Build and Push Docker Images"
echo "====================================="
echo "docker build -t your-registry/dashboard-backend:latest ./backend"
echo "docker push your-registry/dashboard-backend:latest"
echo ""
echo "docker build -t your-registry/dashboard-frontend:latest ./frontend"
echo "docker push your-registry/dashboard-frontend:latest"
echo ""

echo "Step 5: Deploy to Kubernetes"
echo "============================"
echo "cd Dashboard/k8s"
echo "chmod +x deploy.sh"
echo "./deploy.sh"
echo ""
echo "Or manually:"
echo "  kubectl apply -f namespace.yaml"
echo "  kubectl apply -f configmap.yaml"
echo "  kubectl apply -f secret.yaml"
echo "  kubectl apply -f redis.yaml"
echo "  kubectl apply -f backend.yaml"
echo "  kubectl apply -f frontend.yaml"
echo "  kubectl apply -f ingress.yaml"
echo ""

echo "Step 6: Verify Deployment"
echo "========================="
echo "kubectl get pods -n dashboard"
echo "kubectl get services -n dashboard"
echo "kubectl logs -f deployment/dashboard-backend -n dashboard"
echo ""

echo "✅ Setup Complete!"
echo ""
echo "API Endpoints:"
echo "  GET  /api/hive/predictions - Get analytics.predictions data"
echo "  GET  /api/hive/tables - List tables in analytics database"
echo "  GET  /api/hive/table/:name - Query specific table"
echo "  POST /api/hive/cache/invalidate - Clear cache"
echo ""
echo "Example Requests:"
echo "  curl http://localhost:3000/api/hive/predictions?limit=100"
echo "  curl http://localhost:3000/api/hive/predictions?municipality=Copenhagen&limit=100"
echo "  curl http://localhost:3000/api/hive/predictions?startDate=2024-01-01&endDate=2024-12-31"
