apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-enricher
  namespace: bd-gr-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-enricher
  template:
    metadata:
      labels:
        app: kafka-enricher
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: kafka-enricher
          image: registry.gitlab.sdu.dk/the-european-avengers/bigdataproject/kafka-enricher:latest
          imagePullPolicy: Always
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka-g5:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8081"
            - name: CHECKPOINT_ROOT
              value: "/tmp/spark/checkpoints/kafka_enricher_v12"
            - name: HDFS_NAMENODE
              value: "hdfs://namenode-g5-ha"
            - name: HADOOP_CONF_fs_defaultFS
              value: "hdfs://namenode-g5-ha"
            - name: MUNICIPALITY_CSV_HDFS
              value: "hdfs://namenode-g5-ha/utils/municipality_codes_to_coordinates.csv"
            - name: HADOOP_CONF_DIR
              value: "/etc/hadoop/conf"
          volumeMounts:
            - name: hadoop-xml-volume
              mountPath: "/etc/hadoop/conf/core-site.xml"
              subPath: "core-site.xml"
            - name: hadoop-xml-volume
              mountPath: "/etc/hadoop/conf/hdfs-site.xml"
              subPath: "hdfs-site.xml"
          ports:
            - containerPort: 4040
          readinessProbe:
            exec:
              command: ["bash", "-c", "pgrep -f 'spark' > /dev/null"]
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["bash", "-c", "pgrep -f 'spark' > /dev/null"]
            initialDelaySeconds: 90
            periodSeconds: 20
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: hadoop-xml-volume
          configMap:
            name: hadoop-xml-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-enricher
  namespace: bd-gr-05
  labels:
    app: kafka-enricher
spec:
  selector:
    app: kafka-enricher
  ports:
    - name: spark-ui
      port: 4040
      targetPort: 4040
  type: ClusterIP