apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"labels":{"app":"energy-ml-predictor","prediction-month":"2025-12"},"name":"energy-ml-predictor-dec2025","namespace":"bd-bd-gr-05"},"spec":{"backoffLimit":2,"template":{"metadata":{"labels":{"app":"energy-ml-predictor","component":"spark-job","prediction-month":"2025-12"}},"spec":{"containers":[{"args":["spark-submit \\\n  --master local[2] \\\n  --driver-memory 4g \\\n  --executor-memory 4g \\\n  --conf spark.driver.maxResultSize=1g \\\n  --conf spark.sql.shuffle.partitions=16 \\\n  --conf spark.default.parallelism=16 \\\n  --conf spark.executor.cores=4 \\\n  --conf spark.sql.adaptive.enabled=true \\\n  --conf spark.sql.adaptive.coalescePartitions.enabled=true \\\n  --packages org.apache.spark:spark-avro_2.12:3.5.0 \\\n  /opt/spark/work-dir/src/main.py \\\n  --days \"2025-12-01,2025-12-02,2025-12-03,2025-12-04,2025-12-05,2025-12-06,2025-12-07,2025-12-08,2025-12-09,2025-12-10,2025-12-11,2025-12-12,2025-12-13,2025-12-14,2025-12-15,2025-12-16,2025-12-17,2025-12-18,2025-12-19,2025-12-20,2025-12-21,2025-12-22,2025-12-23,2025-12-24,2025-12-25,2025-12-26,2025-12-27,2025-12-28,2025-12-29,2025-12-30,2025-12-31\" \\\n  --training-years 3 \\\n  --mode kubernetes\n"],"command":["/bin/bash","-c"],"env":[{"name":"PYTHONUNBUFFERED","value":"1"},{"name":"SPARK_DRIVER_MEMORY","value":"4g"},{"name":"SPARK_EXECUTOR_MEMORY","value":"4g"}],"envFrom":[{"configMapRef":{"name":"energy-ml-config"}}],"image":"registry.gitlab.sdu.dk/the-european-avengers/bigdataproject/energy-ml-predictor:latest","imagePullPolicy":"Always","name":"spark-driver","resources":{"limits":{"cpu":"2000m","memory":"7Gi"},"requests":{"cpu":"1000m","memory":"6Gi"}},"volumeMounts":[{"mountPath":"/data","name":"data-volume"}]}],"restartPolicy":"OnFailure","volumes":[{"name":"data-volume","persistentVolumeClaim":{"claimName":"energy-data-pvc"}}]}},"ttlSecondsAfterFinished":86400}}
  creationTimestamp: "2025-12-09T21:35:50Z"
  generation: 1
  labels:
    app: energy-ml-predictor
    prediction-month: 2025-12
  name: energy-ml-predictor-dec2025
  namespace: bd-bd-gr-05
  resourceVersion: "25268617"
  uid: 453635bc-a4ad-48de-ac11-1df1374a671d
spec:
  backoffLimit: 2
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 453635bc-a4ad-48de-ac11-1df1374a671d
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: energy-ml-predictor
        batch.kubernetes.io/controller-uid: 453635bc-a4ad-48de-ac11-1df1374a671d
        batch.kubernetes.io/job-name: energy-ml-predictor-dec2025
        component: spark-job
        controller-uid: 453635bc-a4ad-48de-ac11-1df1374a671d
        job-name: energy-ml-predictor-dec2025
        prediction-month: 2025-12
    spec:
      containers:
      - args:
        - |
          spark-submit \
            --master local[2] \
            --driver-memory 4g \
            --executor-memory 4g \
            --conf spark.driver.maxResultSize=1g \
            --conf spark.sql.shuffle.partitions=16 \
            --conf spark.default.parallelism=16 \
            --conf spark.executor.cores=4 \
            --conf spark.sql.adaptive.enabled=true \
            --conf spark.sql.adaptive.coalescePartitions.enabled=true \
            --packages org.apache.spark:spark-avro_2.12:3.5.0 \
            /opt/spark/work-dir/src/main.py \
            --days "2025-12-01,2025-12-02,2025-12-03,2025-12-04,2025-12-05,2025-12-06,2025-12-07,2025-12-08,2025-12-09,2025-12-10,2025-12-11,2025-12-12,2025-12-13,2025-12-14,2025-12-15,2025-12-16,2025-12-17,2025-12-18,2025-12-19,2025-12-20,2025-12-21,2025-12-22,2025-12-23,2025-12-24,2025-12-25,2025-12-26,2025-12-27,2025-12-28,2025-12-29,2025-12-30,2025-12-31" \
            --training-years 3 \
            --mode kubernetes
        command:
        - /bin/bash
        - -c
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: SPARK_DRIVER_MEMORY
          value: 4g
        - name: SPARK_EXECUTOR_MEMORY
          value: 4g
        envFrom:
        - configMapRef:
            name: energy-ml-config
        image: registry.gitlab.sdu.dk/the-european-avengers/bigdataproject/energy-ml-predictor:latest
        imagePullPolicy: Always
        name: spark-driver
        resources:
          limits:
            cpu: "2"
            memory: 7Gi
          requests:
            cpu: "1"
            memory: 6Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data-volume
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: energy-data-pvc
  ttlSecondsAfterFinished: 86400
status:
  active: 1
  ready: 0
  startTime: "2025-12-09T21:35:50Z"
  terminating: 0
  uncountedTerminatedPods: {}
