# kafka-values.yaml
image:
  registry: docker.io
  repository: bitnamilegacy/kafka
  tag: 3.9.0-debian-12-r1

kraft:
  enabled: true

controller:
  replicaCount: 3
  
  # ADD THIS SECTION - Force custom resources
  resourcesPreset: "none"  # Disable preset
  resources:
    requests:
      memory: "4Gi"
      cpu: "1000m"
    limits:
      memory: "8Gi"
      cpu: "2000m"
  
listeners:
  client:
    name: CLIENT
    protocol: PLAINTEXT
    containerPort: 9092
  internal:
    name: INTERNAL
    protocol: PLAINTEXT
    containerPort: 9094
  controller:
    name: CONTROLLER
    protocol: PLAINTEXT
    containerPort: 9093

advertisedListeners: "CLIENT://kafka-g5-controller-$(POD_NAME).kafka-g5-controller-headless.bd-bd-gr-05.svc.cluster.local:9092"

controllerQuorumVoters: "0@kafka-g5-controller-0.kafka-g5-controller-headless.bd-bd-gr-05.svc.cluster.local:9093,1@kafka-g5-controller-1.kafka-g5-controller-headless.bd-bd-gr-05.svc.cluster.local:9093,2@kafka-g5-controller-2.kafka-g5-controller-headless.bd-bd-gr-05.svc.cluster.local:9093"

persistence:
  enabled: true
  size: 8Gi

defaultReplicationFactor: 3
minInsyncReplicas: 2