name: Discord PR notify
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check DISCORD_WEBHOOK presence (safe)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ -z "$DISCORD_WEBHOOK" ]; then
            echo "DISCORD_WEBHOOK is EMPTY (secret missing)"
            exit 1
          else
            echo "DISCORD_WEBHOOK is SET"
          fi

      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: "New PR: {{ EVENT_PAYLOAD.pull_request.title }} by {{ EVENT_PAYLOAD.pull_request.user.login }} — {{ EVENT_PAYLOAD.pull_request.html_url }}"
